export const categoryData = {
  1: [ // Cafes
    { id: 1, name: "Roastery Coffee House", location: "Banjara Hills", rating: 4.5},
    { id: 2, name: "Karachi Bakery Cafe", location: "Banjara Hills", rating: 4.2 },
    { id: 3, name: "Autumn Leaf Cafe", location: "Jubilee Hills", rating: 4.4 },
    { id: 4, name: "Chai Point", location: "Gachibowli", rating: 4.1 },
    { id: 5, name: "The Coffee Cup", location: "Banjara Hills", rating: 4.3 },
    { id: 6, name: "Cafe Bahar", location: "Madhapur", rating: 4.0 },
    { id: 7, name: "Cafe Coffee Day", location: "HITEC City", rating: 3.9 },
    { id: 8, name: "The Indian Coffee House", location: "Abids", rating: 4.1 },
    { id: 9, name: "Cafe 555", location: "Himayat Nagar", rating: 4.0 },
    { id: 10, name: "Bean Here", location: "Kondapur", rating: 4.2 },
    { id: 11, name: "The Art House Cafe", location: "Banjara Hills", rating: 4.3 },
    { id: 12, name: "The Coffee Shop", location: "KPHB", rating: 4.1 },
    { id: 13, name: "Cafe Dori", location: "Jubilee Hills", rating: 4.4 },
    { id: 14, name: "Chai Kaapi", location: "Madhapur", rating: 4.0 },
    { id: 15, name: "Brewmeister", location: "Jubilee Hills", rating: 4.5 }
  ],
  2: [ // Hospitals
    { id: 1, name: "Apollo Hospitals", location: "Jubilee Hills", rating: 4.6 },
    { id: 2, name: "Care Hospitals", location: "Banjara Hills", rating: 4.3 },
    { id: 3, name: "Yashoda Hospitals", location: "Secunderabad", rating: 4.4 },
    { id: 4, name: "MaxCure Hospitals", location: "Madhapur", rating: 4.2 },
    { id: 5, name: "Medicure Hospitals", location: "Gachibowli", rating: 4.1 },
    { id: 6, name: "AIG Hospitals", location: "Gachibowli", rating: 4.5 },
    { id: 7, name: "Rainbow Children's Hospital", location: "Banjara Hills", rating: 4.4 },
    { id: 8, name: "Sapphire Hospitals", location: "Kondapur", rating: 4.2 },
    { id: 9, name: "NIMS Hospitals", location: "Panjagutta", rating: 4.3 },
    { id: 10, name: "Osmania General Hospital", location: "Hyderabad", rating: 4.0 },
    { id: 11, name: "KIMS Hospitals", location: "Secunderabad", rating: 4.4 },
    { id: 12, name: "Swathi Hospitals", location: "Himayat Nagar", rating: 4.1 },
    { id: 13, name: "Hyderabad Hospitals", location: "Jubilee Hills", rating: 4.3 },
    { id: 14, name: "Star Hospitals", location: "Madhapur", rating: 4.2 },
    { id: 15, name: "Bharati Hospitals", location: "Hitech City", rating: 4.0 }
  ],
  3: [ // Transport
    { id: 1, name: "Mahatma Gandhi Bus Station (MGBS)", location: "Gowliguda", type: "Bus" },
    { id: 2, name: "Secunderabad Railway Station", location: "Secunderabad", type: "Train" },
    { id: 3, name: "Rajiv Gandhi International Airport", location: "Shamshabad", type: "Airport" },
    { id: 4, name: "Jubilee Hills Bus Station", location: "Jubilee Hills", type: "Bus" },
    { id: 5, name: "HITEC City Metro Station", location: "HITEC City", type: "Metro" },
    { id: 6, name: "MG Bus Station", location: "MG Road", type: "Bus" },
    { id: 7, name: "Secunderabad East Railway Station", location: "Secunderabad", type: "Train" },
    { id: 8, name: "Shamsabad Bus Station", location: "Shamsabad", type: "Bus" },
    { id: 9, name: "Koti Bus Station", location: "Koti", type: "Bus" },
    { id: 10, name: "Begumpet Railway Station", location: "Begumpet", type: "Train" },
    { id: 11, name: "Lingampally Bus Station", location: "Lingampally", type: "Bus" },
    { id: 12, name: "L.B. Nagar Metro Station", location: "L.B. Nagar", type: "Metro" },
    { id: 13, name: "Gachibowli Bus Station", location: "Gachibowli", type: "Bus" },
    { id: 14, name: "Uppal Metro Station", location: "Uppal", type: "Metro" },
    { id: 15, name: "Hitech City Railway Station", location: "Hitech City", type: "Train" }
  ],
  4: [ // Hotels
    { id: 1, name: "Taj Falaknuma Palace", location: "Engine Bowli", rating: 4.8 },
    { id: 2, name: "ITC Kohenur", location: "Madhapur", rating: 4.6 },
    { id: 3, name: "The Westin Hyderabad", location: "Mindspace IT Park", rating: 4.5 },
    { id: 4, name: "Sheraton Hyderabad", location: "Gachibowli", rating: 4.7 },
    { id: 5, name: "Radisson Blu Plaza", location: "Banjara Hills", rating: 4.6 },
    { id: 6, name: "Hyatt Hyderabad", location: "Gachibowli", rating: 4.5 },
    { id: 7, name: "Trident Hyderabad", location: "HITEC City", rating: 4.4 },
    { id: 8, name: "The Park Hyderabad", location: "Banjara Hills", rating: 4.3 },
    { id: 9, name: "Novotel Hyderabad", location: "HITEC City", rating: 4.2 },
    { id: 10, name: "Holiday Inn", location: "Madhapur", rating: 4.1 },
    { id: 11, name: "Hotel Green Park", location: "Begumpet", rating: 4.3 },
    { id: 12, name: "Ibis Hyderabad", location: "HITEC City", rating: 4.0 },
    { id: 13, name: "Courtyard by Marriott", location: "Gachibowli", rating: 4.2 },
    { id: 14, name: "The Lemon Tree", location: "Madhapur", rating: 4.1 },
    { id: 15, name: "Grand Hyatt Hyderabad", location: "Banjara Hills", rating: 4.5 }
  ],
  5: [ // Educational Institutions
    { id: 1, name: "University of Hyderabad", location: "Gachibowli", type: "University" },
    { id: 2, name: "Osmania University", location: "Amberpet", type: "University" },
    { id: 3, name: "Indian School of Business", location: "Gachibowli", type: "Business School" },
    { id: 4, name: "Jawaharlal Nehru Technological University", location: "Hyderabad", type: "University" },
    { id: 5, name: "National Institute of Technology", location: "Warangal", type: "Institute" },
    { id: 6, name: "Indian Institute of Technology", location: "Hyderabad", type: "Institute" },
    { id: 7, name: "International Institute of Information Technology", location: "Gachibowli", type: "Institute" },
    { id: 8, name: "Hyderabad Central University", location: "Gachibowli", type: "University" },
    { id: 9, name: "Manipal University", location: "Hyderabad", type: "University" },
    { id: 10, name: "Bharat Institute of Engineering and Technology", location: "IBS", type: "Engineering College" },
    { id: 11, name: "NALSAR University of Law", location: "Shamshabad", type: "Law School" },
    { id: 12, name: "National Institute of Fashion Technology", location: "Hyderabad", type: "Institute" },
    { id: 13, name: "Shadan College of Engineering and Technology", location: "Hyderabad", type: "Engineering College" },
    { id: 14, name: "CVR College of Engineering", location: "Hyderabad", type: "Engineering College" },
    { id: 15, name: "Keshav Memorial Institute of Technology", location: "Hyderabad", type: "Engineering College" }
  ],
  6: [ // Petrol Bunks
    { id: 1, name: "Indian Oil", location: "Banjara Hills", type: "Petrol" },
    { id: 2, name: "Bharat Petroleum", location: "Jubilee Hills", type: "Petrol" },
    { id: 3, name: "Hindustan Petroleum", location: "Secunderabad", type: "Petrol" },
    { id: 4, name: "Shell", location: "HITEC City", type: "Petrol" },
    { id: 5, name: "Essar", location: "Madhapur", type: "Petrol" },
    { id: 6, name: "Reliance", location: "Kondapur", type: "Petrol" },
    { id: 7, name: "Total", location: "Gachibowli", type: "Petrol" },
    { id: 8, name: "BPCL", location: "Himayat Nagar", type: "Petrol" },
    { id: 9, name: "HPCL", location: "Shamshabad", type: "Petrol" },
    { id: 10, name: "IOCL", location: "Gachibowli", type: "Petrol" },
    { id: 11, name: "ECS", location: "Begumpet", type: "Petrol" },
    { id: 12, name: "VST", location: "Banjara Hills", type: "Petrol" },
    { id: 13, name: "Essar Petroleum", location: "Secunderabad", type: "Petrol" },
    { id: 14, name: "Reliance Petroleum", location: "Jubilee Hills", type: "Petrol" },
    { id: 15, name: "Indian Oil Corporation", location: "Madhapur", type: "Petrol" }
  ],
  7: [ // Police Stations
    { id: 1, name: "Banjara Hills Police Station", location: "Banjara Hills", type: "Local" },
    { id: 2, name: "Jubilee Hills Police Station", location: "Jubilee Hills", type: "Local" },
    { id: 3, name: "Madhapur Police Station", location: "Madhapur", type: "Local" },
    { id: 4, name: "Gachibowli Police Station", location: "Gachibowli", type: "Local" },
    { id: 5, name: "HITEC City Police Station", location: "HITEC City", type: "Local" },
    { id: 6, name: "Shamshabad Police Station", location: "Shamshabad", type: "Local" },
    { id: 7, name: "Secunderabad Police Station", location: "Secunderabad", type: "Local" },
    { id: 8, name: "Abids Police Station", location: "Abids", type: "Local" },
    { id: 9, name: "Begumpet Police Station", location: "Begumpet", type: "Local" },
    { id: 10, name: "Kondapur Police Station", location: "Kondapur", type: "Local" },
    { id: 11, name: "Malkajgiri Police Station", location: "Malkajgiri", type: "Local" },
    { id: 12, name: "LB Nagar Police Station", location: "LB Nagar", type: "Local" },
    { id: 13, name: "Jubilee Hills Road Police Station", location: "Jubilee Hills", type: "Local" },
    { id: 14, name: "Narayanaguda Police Station", location: "Narayanaguda", type: "Local" },
    { id: 15, name: "Dilsukhnagar Police Station", location: "Dilsukhnagar", type: "Local" }
  ]
};
