name: GKE Resource Cleanup (No State)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    container:
      image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Delete GKE Node Pool
      run: |
        gcloud container node-pools delete react-node-pool \
          --cluster=react-gke-cluster \
          --zone=us-central1-a \
          --quiet || echo "Node pool may already be deleted"

    - name: Delete GKE Cluster
      run: |
        gcloud container clusters delete react-gke-cluster \
          --zone=us-central1-a \
          --quiet || echo "Cluster may already be deleted"

    - name: Delete VPC Network
      run: |
        gcloud compute networks delete react-app-vpc \
          --quiet || echo "VPC network may already be deleted"
