name: GCP Force Delete Resources

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  gcp-cleanup:
    runs-on: ubuntu-latest

    container:
      image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/zone ${{ secrets.GCP_ZONE }}
        gcloud config set compute/region ${{ secrets.GCP_REGION }}

    - name: Verify Cluster Exists
      run: |
        echo "🔍 Checking GKE cluster existence..."
        gcloud container clusters list

    - name: Delete Node Pool
      run: |
        echo " Deleting node pool (if exists)..."
        gcloud container node-pools delete react-node-pool \
          --cluster=react-gke-cluster \
          --zone=${{ secrets.GCP_ZONE }} \
          --quiet || echo "⚠️ Node pool not found or already deleted."

    - name: Delete GKE Cluster
      run: |
        echo "Deleting GKE cluster (if exists)..."
        gcloud container clusters delete react-gke-cluster \
          --zone=${{ secrets.GCP_ZONE }} \
          --quiet || echo "⚠️ Cluster not found or already deleted."

    - name: Verify Network Exists
      run: |
        echo "🔍 Listing networks..."
        gcloud compute networks list

    - name: Delete VPC Network
      run: |
        echo " Deleting VPC network (if exists)..."
        gcloud compute networks delete react-app-vpc \
          --quiet || echo "⚠️ VPC network not found or already deleted."
